//===-- Types.h - EDA Type Declarations ---------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef EDA_TYPES_H
#define EDA_TYPES_H

#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Types.h"
#include "mlir/Interfaces/DataLayoutInterfaces.h"

namespace eda {
class EDADialect;
}

// Type declarations will be generated by TableGen
// The generated code defines types in the eda namespace and TypeID declarations in the global namespace
#define GET_TYPEDEF_CLASSES
#include "eda-dialect/EDATypes.h.inc"

#endif // EDA_TYPES_H